import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { LoginHistoryOrderByWithRelationInputObjectSchema as LoginHistoryOrderByWithRelationInputObjectSchema } from './objects/LoginHistoryOrderByWithRelationInput.schema';
import { LoginHistoryWhereInputObjectSchema as LoginHistoryWhereInputObjectSchema } from './objects/LoginHistoryWhereInput.schema';
import { LoginHistoryWhereUniqueInputObjectSchema as LoginHistoryWhereUniqueInputObjectSchema } from './objects/LoginHistoryWhereUniqueInput.schema';
import { LoginHistoryCountAggregateInputObjectSchema as LoginHistoryCountAggregateInputObjectSchema } from './objects/LoginHistoryCountAggregateInput.schema';
import { LoginHistoryMinAggregateInputObjectSchema as LoginHistoryMinAggregateInputObjectSchema } from './objects/LoginHistoryMinAggregateInput.schema';
import { LoginHistoryMaxAggregateInputObjectSchema as LoginHistoryMaxAggregateInputObjectSchema } from './objects/LoginHistoryMaxAggregateInput.schema';

export const LoginHistoryAggregateSchema: z.ZodType<Prisma.LoginHistoryAggregateArgs> = z.object({ orderBy: z.union([LoginHistoryOrderByWithRelationInputObjectSchema, LoginHistoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: LoginHistoryWhereInputObjectSchema.optional(), cursor: LoginHistoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LoginHistoryCountAggregateInputObjectSchema ]).optional(), _min: LoginHistoryMinAggregateInputObjectSchema.optional(), _max: LoginHistoryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.LoginHistoryAggregateArgs>;

export const LoginHistoryAggregateZodSchema = z.object({ orderBy: z.union([LoginHistoryOrderByWithRelationInputObjectSchema, LoginHistoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: LoginHistoryWhereInputObjectSchema.optional(), cursor: LoginHistoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), LoginHistoryCountAggregateInputObjectSchema ]).optional(), _min: LoginHistoryMinAggregateInputObjectSchema.optional(), _max: LoginHistoryMaxAggregateInputObjectSchema.optional() }).strict();